### ISSUE TITLE
Example patches don't appear in Files after moving the download to a new location

### ISSUE THREAD

**Issue by ideoforms** [playbenny/benny#464]
On first install, I opened benny from my `Downloads` folder and it worked great. I then moved it to a new location and it no longer opens, with no error messages. Maybe related to #461 ?

**Comment by jamesholdenmusic** [comment]
i can't recreate this one on windows - i tried taking a new download of it, running once, closing, moving it somewhere else, and it opened fine in the new location. does opening the benny.maxproj file even open max/msp? definitely nothing in the console?

if you delete userconfig.json after moving does it work? (this retriggers all the first run actions, which are mostly populating userconfig with defaults)

is it maybe something about your mac protecting you from a download from the internet? (ie if you fetch it using git instead of a browser then move it does this still happen?)

i think 461 is unrelated (i'm 100% that one is down to me not thinking it through)

**Comment by ideoforms** [comment]
I've just re-downloaded the latest, and not been able to reproduce, so will close this. Not sure if it was something resolved since, or something to do with my original download/setup, but Benny now opens fine in new locations. The only issue is that, after relocating it, it no longer see the example patches (`lpgs`, `reson`, etc), which maybe _is_ to do with #461 ?

**Comment by jamesholdenmusic** [comment]
reopening so i rememeber to fix that last bit. i think it should check to see if it can find the stored folder locations and if not i guess it should re-insert the default ones.

**Comment by ideoforms** [comment]
thanks!
