### ISSUE TITLE
**Issue with Twister as Main CC Controller**

### ISSUE THREAD

**Issue by bmd-jpreiksa** [playbenny/benny#536]
Hi,

I've been trying to use the MIDI  Fighter Twister as the main CC controller with Benny for the past few days, but I'm encountering some issues. The Twister either does not send CC data to Benny, or when it does, Benny's responses are very jumpy, laggy, and inconsistent.

Is there a specific Twister configuration that I should be using? Should I configure it outside of Benny? 

For reference, I'm using an OSX M1 setup.

Thanks in advance!

**Comment by jamesholdenmusic** [comment]
hey, thanks for pointing this out - i had forgotten to include the settings file for the midi fighter. i just pushed an update and if you look in benny/hardware_configs/preset files for common controllers there's one there, you can load it on using their mf utility software.

(i've been using it with the knobs set to encoder output mode rather than the pot-emulation they have as a default.)

there are examples of the right benny settings for these midi fighter twister settings in my config files (eg no_hardware.json)

if that doesn't help, post the hardware configuration .json file you're using here

**Comment by bmd-jpreiksa** [comment]
Hey, thanks for the quick update! The configuration file was just what I needed—really appreciate it!

By the way, I’ll be putting Benny through some testing by performing live with it at the GAIDA festival in Vilnius on October 25th. If you're interested, you're more than welcome to come and see how your software holds up in the hands of someone else! 😄

**Comment by jamesholdenmusic** [comment]
great! good luck! & if there are any videos I'd love to see..
