### ISSUE TITLE
Issues with panel view

### ISSUE THREAD

**Issue by bmd-jpreiksa** [playbenny/benny#548]
Hey I am running it an issue where panel view does not get properly refreshed after putting a fair amount of devices (including hardware). It does work nicely on demo songs though. 

When I try to interact with panel(mouse click a device) it gets stuck then by pressing TAB twice (changing between block-panel) the panel view is refreshed however it gets stuck again after the first interaction. 
Is there a quick fix. Maybe something in configs that can help?
I am using Mac book M1pro btw. 

Thanks in advance!

**Comment by jamesholdenmusic** [comment]
hey, i haven't seen that happening here before. it'll probably be one tiny thing failing and not being caught. thanks for reporting, let's work out what! and maybe in the process i can make that page more resilient.
can you do 2 things for me:

- have a look in the max console window, immediately after the first click that makes it get stuck, are there any messages or errors printed? when you press tab it'll probably write 'draw blocks' to console, anything else?
- can you attach here both your hardware configuration file AND the song file (both will be .json) then i can load them up and see if i can reproduce the problem

thanks!

**Comment by bmd-jpreiksa** [comment]
1) js: display_pages.js: Javascript TypeError: params[plist[p]] is undefined, line 411
2) js: error calling function frameclock [blockmanager]

here they are:

[gaida_jazz_hardw.json](https://github.com/user-attachments/files/17395781/gaida_jazz_hardw.json)
[jazz3.json](https://github.com/user-attachments/files/17395784/jazz3.json)

**Comment by jamesholdenmusic** [comment]
[jazz3.json](https://github.com/user-attachments/files/17396755/jazz3.json)

got it! i've attached a repaired version of your songfile so you can carry on with music asap..

what it was was the stretch delay had a parameter assigned for its panel view that didnt exist. trying to work out how that occured - do you remember if you swapped that delay block at some point previously? if it was a different block, with more parameters, and then you swapped it, i think i forgot to safety-check the panel assignments during a swap so that could cause this bug. i'll fix that, but if my theory sounds wrong maybe there are two bugs so let me know!

thanks again for reporting this, very useful for me to see how people use benny.

one tiny note: the mix bus is meant to only be fed audio from mix.channel or mix.stereo.channel blocks - they use the airwindows console system for summing: a nonlinear transform is applied at the end of the channel block, then the mix block reverses this - so a single signal comes out the same as it went in, but if two signals are summed in the bus they move each other around the nonlinearity, it gives things a really nice 'desk-y' quality. he explains it better than me on airwindows.com.. 

i definitely need to make a clearer explanation of this in the ui!

here's a screenshot of one of my patches showing the mix.channel / mix.stereo.channels going into the mix.bus.

![image](https://github.com/user-attachments/assets/436cdc08-49fa-4e1a-8d46-8daaeb972b0e)

**Comment by bmd-jpreiksa** [comment]
Thank you!
Using this as a template for all the songs seems to stabilise the whole thing. 
I am not sure how/when this parameter is assigned though. 
Sometimes it happens in the middle of session and sometimes when initialising the song from saved json. I will come back to reproducing this later on to give exact details. 

And thanks for the heads up on mix/bus case!

**Comment by jamesholdenmusic** [comment]
great! glad to hear that.
i'm pretty sure now that the mistake came from an error in my config file
for the stretch delay, the default panel slider assignments were faulty. if
you have more songfiles that need fixing feel free to attach them here (i'm
around all day) as it only takes a minute but explaining how to do it
manually is a bit long. hopefully it won't come back now. (but tell me if
it does)

**Comment by jamesholdenmusic** [comment]
that's great! would have loved to see the whole show. thanks for sending me
the link :) and thanks for the feedback.
for more io i'm using 2x ES-10 (the new module they just released with 8
ins and 8 outs) + es-3 with a RME digiface. the RME drivers are better than
the ES ones and the digiface supports up to 32ins and 32 outs + a bonus
headphone socket that i use for click or for a cue/prelisten. (also there's
an experimental new feature i'm working on that can use the RME's own low
latency routing mixer to make connections between hardware blocks)

**Comment by bmd-jpreiksa** [comment]
Thanks so much for the feedback and advice. Means a lot.
As for seeing a full performance, we’re gearing up to release an album that includes the stuff I showed you.. We’re also planning a Baltic tour this spring: Vilnius, Riga, Tallinn. It would be amazing to share a stage with you and make it something special.
If you’re even a little interested, let’s chat and see if we can make it happen. It would mean a ton to have you on board.

**Comment by jamesholdenmusic** [comment]
do let me know when it's coming out! and thanks for asking that but I think
it'd be hard - we're putting together the tour for my next project in that
time
